name: VeeR-EL2 CI

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:

  Build-Verilator:
    name: Build-Verilator
    uses: ./.github/workflows/build-verilator.yml

  Test-Regression:
    name: Test-Regression
    needs: [Build-Verilator]
    uses: ./.github/workflows/test-regression.yml

  Test-Verification:
    name: Test-Verification
    needs: [Build-Verilator]
    uses: ./.github/workflows/test-verification.yml

  Report-Coverage:
    name: Report-Coverage
    needs: [Test-Regression, Test-Verification]
    uses: ./.github/workflows/report-coverage.yml

  Report-Pytest:
    name: Report-Pytest
    needs: [Test-Verification]
    uses: ./.github/workflows/report-pytest.yml

  Publish-to-GH-Pages:
    permissions:
      actions: write
      contents: write
    name: Publish-to-GH-Pages
    needs: [Report-Coverage, Report-Pytest]
    uses: ./.github/workflows/publish-webpage.yml
