name: VeeR-EL2 CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  Build-Verilator:
    name: Build-Verilator
    uses: ./.github/workflows/build-verilator.yml

  Test-UVM:
    name: Test-UVM
    needs: [Build-Verilator]
    uses: ./.github/workflows/test-uvm.yml
