name: GH-Pages PR Remove Deploy

on:
  workflow_run:
    workflows: ["GH-Pages PR Remove"]
    types:
      - completed

env:
  ROOT_DIR: './public'

jobs:
  remove:
    name: PR Remove Deploy
    concurrency:
      group: gh-pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download deployment
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: ${{ env.ROOT_DIR }}

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: delete_pr_number
          path: ./
          run_id: ${{ github.event.workflow_run.id }}

      - name: Extract PR number
        id: PR
        run: |
          cat delete_pr_number.txt | tee "$GITHUB_OUTPUT"

      - name: Remove data for closed PR
        run: |
          rm -rf ${{ env.ROOT_DIR }}/dev/${{ steps.PR.outputs.number }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.ROOT_DIR }}
          commit_message: "Remove reports from PR#${{ steps.PR.outputs.number }}"
