name: GH-Pages PR Remove

on:
  pull_request:
    types:
      - closed

env:
  ROOT_DIR: './public'

jobs:
  build:
    name: PR Remove
    concurrency:
      group: gh-pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Setup repository
        uses: actions/checkout@v3

      - name: Download release
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: ${{ env.ROOT_DIR }}

      - name: Save PR number
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        run: |
          echo "number=${{ github.event.number }}" >> delete_pr_number.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: github.event_name == 'pull_request'
        with:
          name: delete_pr_number
          path: ./delete_pr_number.txt