name: Coverage report

on:
  workflow_call:

jobs:

  coverage-report:
    name: Coverage report
    runs-on: ubuntu-latest
    container: ghcr.io/antmicro/cores-veer-el2:20241230
    env:
      DEBIAN_FRONTEND: "noninteractive"

    steps:
      - name: Setup repository
        uses: actions/checkout@v3

      - name: Install coverage dependencies
        shell: bash
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r .github/scripts/requirements-coverage.txt
          echo "PATH=$PATH" >> $GITHUB_ENV

        # This step is needed to have the same VeeR codebase as used in tests
      - name: Configure VeeR
        shell: bash
        run: |
          export RV_ROOT=`pwd`
          make defines.h -f $RV_ROOT/tools/Makefile

      - name: Setup lcov
        shell: bash
        run: |
          git clone https://github.com/linux-test-project/lcov
          pushd lcov
            git checkout v2.1
            echo "LCOV_PATH=`realpath bin`" >> "$GITHUB_ENV"
          popd

      - name: Download coverage reports
        uses: actions/download-artifact@v3
        with:
          name: regression_tests_coverage_data
          path: ./

      - name: Download coverage reports
        uses: actions/download-artifact@v3
        with:
          name: verification_tests_coverage_data
          path: ./

      - name: Download coverage reports
        uses: actions/download-artifact@v3
        with:
          name: uarch_tests_coverage_data
          path: ./

      - name: Download coverage reports
        uses: actions/download-artifact@v3
        with:
          name: riscv-dv_coverage_data
          path: ./

      - name: Download coverage reports
        uses: actions/download-artifact@v3
        with:
          name: riscof_coverage_data
          path: ./

      - name: Download coverage reports
        uses: actions/download-artifact@v3
        with:
          name: openocd_coverage_data
          path: ./

      - name: Generate reports
        shell: bash
        run: |
          export PATH=${{ env.LCOV_PATH }}:${PATH}
          sis -d reports . --report-dir report --src-pattern \*design\*
          cat *_toggle.info > coverage.toggle.info
          cat *_branch.info > coverage.branch.info

      - name: Pack artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage_report
          path: ./report

      - name: Pack artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: combined_coverage_data
          path: |
            coverage.toggle.info
            coverage.branch.info

  merge-verilator-reports:
    name: Merge Verilator info data
    runs-on: ubuntu-latest
    container: ghcr.io/antmicro/cores-veer-el2:20241230
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Download coverage reports
        uses: actions/download-artifact@v3
        with:
          name: regression_tests_coverage_data
          path: ./

      - name: Download coverage reports
        uses: actions/download-artifact@v3
        with:
          name: verification_tests_coverage_data
          path: ./

      - name: Download coverage reports
        uses: actions/download-artifact@v3
        with:
          name: uarch_tests_coverage_data
          path: ./

      - name: Download coverage reports
        uses: actions/download-artifact@v3
        with:
          name: riscv-dv_coverage_data
          path: ./

      - name: Download coverage reports
        uses: actions/download-artifact@v3
        with:
          name: riscof_coverage_data
          path: ./

      - name: Download coverage reports
        uses: actions/download-artifact@v3
        with:
          name: openocd_coverage_data
          path: ./

      - name: Merge data
        shell: bash
        run: |
          git clone https://github.com/linux-test-project/lcov -b v2.3-beta
          PATH="`pwd`/lcov/bin:$PATH"
          ls *_toggle.info | xargs printf -- '-a %s\n' | xargs echo | awk '{ print "lcov "$0" --ignore-errors inconsistent --rc lcov_branch_coverage=1 -o coverage_toggle_verilator.info" }' | bash
          ls *_branch.info | xargs printf -- '-a %s\n' | xargs echo | awk '{ print "lcov "$0" --ignore-errors inconsistent -o coverage_line_verilator.info" }' | bash

      - name: Pack artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: verilator_coverage_data
          path: |
            coverage_toggle_verilator.info
            coverage_line_verilator.info

  custom-coverage-report:
    name: Custom coverage report
    runs-on: [ self-hosted, Linux, X64, gcp-custom-runners ]
    container: centos:8
    needs: [merge-verilator-reports]
    env:
      GHA_EXTERNAL_DISK: additional-tools
      GHA_SA: gh-sa-veer-uploader

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Download coverage reports
        uses: actions/download-artifact@v3
        with:
          name: verilator_coverage_data
          path: ./

      - name: Prepare Environment
        run: _secret_prepare_env

      - name: Generate custom report
        run: _secret_custom_report
